import json
import logging
from typing import Any

from pydantic import ValidationError

from schemas.design import DesignSpec
from schemas.validation import VisionReport
from services.llm import LLMService

logger = logging.getLogger("blendpilot.agents.vision_critic")

class VisionCriticAgent:
    """Agent for visually critiquing rendered Blender scenes against intent."""

    def __init__(self, llm_service: LLMService | None = None, mock_mode: bool = False):
        self.llm_service = llm_service or LLMService()
        self.mock_mode = mock_mode

    async def execute(
        self,
        intent: DesignSpec,
        preview_image_path: str,
        scene_summary: dict[str, Any],
    ) -> dict[str, Any]:
        """Critique the rendered image against the original intent."""
        
        # If in mock mode, immediately return a passing validation report
        if self.mock_mode:
            logger.info("VisionCriticAgent running in mock mode. Returning PASS.")
            report = VisionReport(
                object_presence=True,
                required_component_presence=True,
                color_match=True,
                approximate_shape_match=True,
                obvious_visual_errors=[],
                confidence=1.0,
                overall_result="PASS"
            )
            return {"passed": True, "vision_report": report.model_dump()}

        if not self.llm_service.config.api_key and self.llm_service.config.provider != "custom":
            raise ValueError(f"LLM API key is missing for provider '{self.llm_service.config.provider}'. Cannot execute real vision evaluation.")

        prompt = f"""
You are an expert 3D Technical Art Director.
You are evaluating a rendered preview image of a 3D model generated by an automated pipeline.
Your job is to compare the resulting render against the original intent.

ORIGINAL INTENT:
Asset Type: {intent.asset_type}
Style: {intent.style}
Dimensions: {intent.dimensions}
Materials: {intent.materials}
Description: {intent.description}

SCENE SUMMARY:
Objects: {len(scene_summary.get("objects", []))}
Materials: {len(scene_summary.get("materials", []))}

Examine the provided image carefully.
Please provide your critique in the following JSON format ONLY, with no markdown formatting or other text:
{{
    "object_presence": true/false,
    "required_component_presence": true/false,
    "color_match": true/false,
    "approximate_shape_match": true/false,
    "obvious_visual_errors": ["list of strings"],
    "confidence": 0.0 - 1.0,
    "overall_result": "PASS" or "FAIL"
}}

IMPORTANT: Return ONLY the raw JSON string. Do not wrap in ```json ```.
"""
        
        logger.info("Calling vision model for visual critique...")
        try:
            response_text = await self.llm_service.generate_vision(
                prompt=prompt,
                image_paths=[preview_image_path] if preview_image_path else []
            )
            
            # Clean response — strip <think>...</think> reasoning blocks (Qwen)
            cleaned_response = response_text.strip()
            if "<think>" in cleaned_response and "</think>" in cleaned_response:
                think_end = cleaned_response.rfind("</think>")
                cleaned_response = cleaned_response[think_end + len("</think>"):].strip()
            if cleaned_response.startswith("```json"):
                cleaned_response = cleaned_response[7:]
            if cleaned_response.startswith("```"):
                cleaned_response = cleaned_response[3:]
            if cleaned_response.endswith("```"):
                cleaned_response = cleaned_response[:-3]
            cleaned_response = cleaned_response.strip()

            data = json.loads(cleaned_response)
            report = VisionReport.model_validate(data)
            
            return {
                "passed": report.overall_result == "PASS",
                "vision_report": report.model_dump()
            }
        except (json.JSONDecodeError, ValidationError) as e:
            logger.error(f"Failed to parse vision model response: {e}\nResponse: {response_text if 'response_text' in locals() else 'None'}")
            # Fallback on failure
            report = VisionReport(
                overall_result="FAIL",
                obvious_visual_errors=[f"Failed to parse vision critique: {str(e)}"],
                confidence=0.0
            )
            return {
                "passed": False,
                "vision_report": report.model_dump()
            }
        except Exception as e:
            logger.exception(f"Unexpected error during vision critique: {e}")
            report = VisionReport(
                overall_result="FAIL",
                obvious_visual_errors=[f"Unexpected error during critique: {str(e)}"],
                confidence=0.0
            )
            return {
                "passed": False,
                "vision_report": report.model_dump()
            }
